### ISSUE TITLE
feature request: give a hint

### ISSUE THREAD

**Issue by city41** [ekzhang/setwithfriends#1]
This is a neat game and a nice implementation. Thanks for making it!

I'd never heard of Set before seeing this, so it took me a while to get a feel for making sets. I think it'd be nice to have a hint button option, that would perhaps highlight two cards from a set. I think it could help beginners get the set mindset down faster.

Just a suggestion, of course :)

**Comment by ekzhang** [comment]
@city41 Thanks for the suggestion! I'll keep this in mind for the next version.

**Comment by leaderam** [comment]
Is there always a solution? Give a hint is definitely a good idea!
