### ISSUE TITLE
Profile page is slow to load for people with a lot of games

### ISSUE THREAD

**Issue by eltoder** [ekzhang/setwithfriends#103]
Example: https://setwithfriends.com/profile/Q1lOhh0vjGZEAwQzV0TXqqZCRoD3

Some ideas: limit the number of games displayed; do pagination or load on demand; pre-calculate and save stats so that they can be displayed without loading all game data.

**Comment by ekzhang** [comment]
Thanks, this is a known issue. You sound like you have some good ideas, feel free to help implement these.

**Comment by ekzhang** [comment]
I think I know how to fix this with minimal downtime and chance of errors, so I will write something up.
