### ISSUE TITLE
New Game Mode: SET Junior

### ISSUE THREAD

**Issue by shagemey** [ekzhang/setwithfriends#110]
For those who are just getting started with the game, playing with only the solid shaded pieces can be very helpful in learning to identify SETs by removing one of the variables (shading) entirely. Suggesting to create a "Junior" mode here as well. The only change to be made is that the deck will only contain solid cards, all unfilled and hatched cards are removed.

**Comment by ekzhang** [comment]
Thanks for the suggestion, this has come up before, seems like it would be a reasonable alternate game mode. Also related: #81 - which is somewhat of an opposite!

**Comment by lwalker42** [comment]
Just made pull request.
