### ISSUE TITLE
New game mode/option: Deal last card face down

### ISSUE THREAD

**Issue by NilsEnevoldsen** [ekzhang/setwithfriends#111]
My friends and I enjoy dealing the last card face down. As long as no incorrect sets have been taken, the identity of this card can be determined, and players may claim sets that include it as usual.

**Comment by ekzhang** [comment]
Closing because we're not going to add this new feature at this time.

**Comment by eltoder** [comment]
@NilsEnevoldsen do you have to memorize every previously taken card to play this, or is there some shortcut?

**Comment by NilsEnevoldsen** [comment]
There is a shortcut.

<details>
  <summary>Spoiler warning in case you want to figure it out yourself</summary>
  
  When the last cards have been dealt, you can always partition the board into "sets" with respect to each characteristic. For example, if you see four reds, one green, and one face-down card, then the face down card must be purple.
  
</details>

**Comment by eltoder** [comment]
@NilsEnevoldsen that's what I thought, but then I confused myself into thinking this only works in 27 set games.

Do you have a name for this mode?

**Comment by NilsEnevoldsen** [comment]
No, I don't. In casual games with friends, usually the dealer asks "last card face down?" and the other players consent or don't. So I guess I'd call it “Last Card Face Down”.

**Comment by eltoder** [comment]
Thinking a bit more about it, in most games this does not make a difference, right? In most games you can ignore the last card. It only matters in games with fewer than 27 sets where you must use the last card to finish the game. When you play offline, you have to determine this condition yourself, but on swf this is done automatically. So it seems like it will rarely make a difference unless we add the "NO SET" button and require using it to finish the game. Or am I missing something?
