### ISSUE TITLE
Game mode/option: Autopick third card

### ISSUE THREAD

**Issue by NilsEnevoldsen** [ekzhang/setwithfriends#113]
When a player selects two cards, autoselect the third card if it is present.

As this makes spamming easier, there would need to be some anti-spamming rule when playing with untrustworthy opponents (i.e. public games).

**Comment by lwalker42** [comment]
I don't think this should be added.  There are plenty of situations with very similar looking cards where finding the exact set can be difficult and this would allow guessing.  Additionally, this will exacerbate lag in multiplayer games since people can chain sets one after another even faster.

**Comment by ekzhang** [comment]
I don't think we would implement this for the reasons above, so I'm closing this.
