### ISSUE TITLE
Ban the R-word

### ISSUE THREAD

**Issue by sontyv** [ekzhang/setwithfriends#117]
Hi, I heard that you guys use a pre-defined list of words to ban. Could you guys add the R-word to your list of banned words? I'm not sure if any other slurs are still allowed (haven't seen/didn't want to just test them out haha) so this is the only one I can report right now. Thanks!

**Comment by ekzhang** [comment]
What specific word do you mean? Please clarify or submit a PR.

You can edit [src/util.js](https://github.com/ekzhang/setwithfriends/blob/develop/src/util.js) and add the word to the filter.

**Comment by sontyv** [comment]
Ah, I meant the word "retard/retarded". Thanks!
