### ISSUE TITLE
Blank screen issue for loading profiles

### ISSUE THREAD

**Issue by offset-dass** [ekzhang/setwithfriends#128]
When a user is looking at another user's profile, and then clicks on their own (from the top right account link), then the window goes white/blank in certain circumstances. Refreshing the page shows the profile and not the blank screen.

My guess is that it's based on the number of games created or played on the account you are on, perhaps 50? It seemingly works fine for newer accounts, yet does not work for accounts with more games. I have tried this 3 times: on my current main account, my alternate account, and a fresh/new account, which have finished roughly 2000, 100, and 0 games each. The blank screen would appear for the first two scenarios, but not for the third.

I have sent a screen recording of what happens when I do this on my main account,

https://user-images.githubusercontent.com/84308874/119616179-299fc980-bdb5-11eb-8cc2-c9f819b2cfe4.mov

**Comment by ekzhang** [comment]
Thanks, I was able to reproduce this.
