### ISSUE TITLE
Stuck in spectator mode

### ISSUE THREAD

**Issue by beelzebutttt** [ekzhang/setwithfriends#129]
I want to play with another person, but whenever I click the invite link that is sent to me, the game is launched in spectator mode and I cannot play. How do I get out of spectator mode? Thank you!

**Comment by cynthiakedu** [comment]
If you want to actually play, let the other person wait for you to join the game's waiting room (shown below) before pressing the "START GAME" button. If you join the game after the game is started, you become a spectator and can't get out of it.
<img width="1145" alt="Screen Shot 2021-06-03 at 11 23 27 AM" src="https://user-images.githubusercontent.com/47993494/120670210-32039e80-c45e-11eb-99a3-e686d8fd8acc.png">
