### ISSUE TITLE
Unable to finish a set - no shut off or quit button

### ISSUE THREAD

**Issue by ktxmatrix** [ekzhang/setwithfriends#13]
We love this game and had a fantastic time with our friends. Sadly we got stuck at the end and could not call it quits after 30 minutes of trying to complete a set. So the issue is a 2 part one:

1. Can you put a "We give up" button with a confirmation dialog to allow users to finish a game and see the last set they were missing.
2. Let me know if there is actually a set left or its a bug with the picture I attached. We are pulling our hairs out.

Once again, we love what you have done. So simple and neat. 
<img width="1440" alt="set_issue" src="https://user-images.githubusercontent.com/126864/83368375-917c2980-a386-11ea-9e86-500f9c4b8253.png">

**Comment by cynthiakedu** [comment]
Glad that you enjoyed the game!

Indeed there is no set. The game page did not reflect this due to a race condition that can happen when two players take the last two sets at around the same time. This issue is fixed in #11 .
