### ISSUE TITLE
Sets are not sets

### ISSUE THREAD

**Issue by Const4ntin3** [ekzhang/setwithfriends#134]
Hi,
I just found out about your online game today.
I am only wondering about one thing.
Why is this a set?

![image](https://user-images.githubusercontent.com/7338226/127207863-c2d0b02f-4d07-47a6-a256-3e6ad1de111e.png)

I just looked up the rules of the game which I have at home and it clearly states that "either a set has 3 times just the same or 3 time completely different features".

However, the example included shows, that it has 2 different features (all occur twice, all are pink) and 2 equal features (each with a different filling, each with a different form).
So, this should not be a set.

If I am wrong, could you please explain what I am overlooking?

Thanks!

**Comment by cynthiakedu** [comment]
I think the rules you have at home may be a bit misleading and caused some misunderstanding. 

The actual rule is that, for each of the four features (number of occurrences, color, filling, form), the 3 cards must be all the same or all different for that particular feature. 

As you have identified, for both the number of occurrences and color, they are all the same; for filling and form, they are all different. So this is indeed a set.

If you are still confused, take a look at the rules we have written (https://setwithfriends.com/help), it can help clarify more. Have fun playing!
