### ISSUE TITLE
Game mode: race against the clock (or catchier name)

### ISSUE THREAD

**Issue by jack67889** [ekzhang/setwithfriends#137]
A lot of people on the site seem to enjoy playing solo games. Since it's currently quite different from playing multiplayer games I would suggest to add a multiplayer quasi-solo mode: race against the clock.

Where all the players get the same deck of cards, start at the same time and counters next to the board show how many sets other players got already. It's a nice way to directly compare solo efforts, compared to the current situation where solo records are played on completely different shuffles of course. (Could also be nice for spectators to show a split screen.)

**Comment by ekzhang** [comment]
That's a cool idea! I'm not sure how we'd integrate it with the rest of the site, but it's definitely an interesting game concept.

**Comment by ekzhang** [comment]
Closing because we're not going to add this new feature at this time. It's too different from the rest of the site, and currently we're in maintenance mode.

**Comment by eltoder** [comment]
@jack67889 the downside of the mode is that if players' speeds are significantly different, the faster players will have to wait for the slower players to finish. This can be annoying, and realistically they'll probably start a new game, or the slower players will quit and the game will never finish. Have you thought addressing this?
