### ISSUE TITLE
Possible Tutorial/Instruction Manual

### ISSUE THREAD

**Issue by AOShalash** [ekzhang/setwithfriends#140]
This is more of a simple possible addition and shouldn't require all too much but maybe an information tab or a page on how to play the game as well as the other game modes included. When I first wanted to play ultraset, I just joined a public ultraset match and figured it out but I assume an info tab wouldn't take much and would be a good addition to make.

**Comment by ekzhang** [comment]
We have an information page at https://setwithfriends.com/help, linked at the bottom of the site.
