### ISSUE TITLE
Calling Sets with timer, penalties

### ISSUE THREAD

**Issue by darryllee** [ekzhang/setwithfriends#152]
LOVE LOVE LOVE the project. So yesterday I was in the car with my son thinking and then talking about how it'd be cool to be able to play Set while waiting in line together at Disneyland, for a restaurant, whatever.

And lo and behold, of course somebody already did it. You guys!

So we tried it, and it was great. But when we play in person, we do play by the rule that you have to call SET before you can pickup and then you get penalized a point if 1) you do not pick up a set within a few seconds or 2) the cards are not a set.

I actually talked through the idea with my son about there being a (SET!) button you'd have to hit that locks everyone else out of the board, tells everybody that Player X has called SET, and then you have like, 3-5 seconds to select your cards.

I recognize that if you're playing on a computer with keyboard shortcuts(!), y'all are probably speed demons and aren't looking for anything to slow you down, but I think it'd be a nice option to have "Box Rules" ("Timed/Penalty Rules"?) for us "social" players.

Thanks!!

**Comment by ekzhang** [comment]
Closing because we're not going to add this new feature at this time.

This is a good interface! playset.netlify.app implements it this way for instance. It discourages people from taking sets until they're actually ready. But it's too much to change for Set with Friends at this point.
