### ISSUE TITLE
Custom card images

### ISSUE THREAD

**Issue by EugeniaBogacheva** [ekzhang/setwithfriends#155]
I wonder if it would be possible not only to customize the color of the cards but also the images? I enjoy playing set with my friend and I would like to draw shapes referencing some local jokes that we share to replace the standard squiggles, ovals, and diamonds with custom images referencing some local jokes that we share. It would also be nice to use theme sets of images for Christmas, different seasons etc.

**Comment by ekzhang** [comment]
Closing because we're not going to add this new feature at this time.
