### ISSUE TITLE
banned users aren't actually restricted in any way

### ISSUE THREAD

**Issue by mathmil** [ekzhang/setwithfriends#158]
Today [this user](https://setwithfriends.com/profile/VL1Wj1ZlZvZo0oX8TueIpiq5SxS2) has fully automated joining all public and getting all (normal) sets in under a second, rendering public games completely unusable. They have been banned, but this has no effect since the ban status is never checked server-side.
I think adding `&& root.child('users').child(auth.uid).child('banned').val() < now` to database.rules.json on anything banned users aren't supposed to do (e.g. l16, joining games) should fix this (I haven't tested this though).

**Comment by ekzhang** [comment]
Good point about checking `< now`
