### ISSUE TITLE
firefox sometimes displays incorrect game state

### ISSUE THREAD

**Issue by mathmil** [ekzhang/setwithfriends#159]
When two overlapping SETs have been found in the same millisecond, both are saved but only one is valid.
Firefox thinks the wrong SET to be valid (in comparison to chrome/the server).
One consequence of this is that it can be impossible to finish the game from firefox, with no more SETs being visible.
Two overlapping SETs being found in the same millisecond is really rare in practice, I only know of 10 occurrence of this bug in practice, so it's probably not high priority.
https://setwithfriends.com/game/bouncy-tall-eyes-12 (time of overlapping set: 22.59 1668895295004) is the first occurrence i know of, others are listed on [discord](https://discordapp.com/channels/718326911583125544/1182034926527328337)
The bug can easily recreated in the local emulator by manually editing the database, but is hard to recreate with normal gameplay.

**Comment by ekzhang** [comment]
I looked at the code but not sure where the discrepancy is :( let me know if you have more details!

**Comment by mathmil** [comment]
https://github.com/eltoder/setwithfriends/issues/46
