### ISSUE TITLE
“Help” rules have typo.

### ISSUE THREAD

**Issue by amcdevitt97** [ekzhang/setwithfriends#19]
In production, under “help” the rules are given. A bit further down an explanation on an incorrect triplets. It mentions two red cards and a third green card, but the diagram has two orange cards and a second green card. 

Very silly and pedantic issue but could be confusing for newcomers. Not sure if this is the same in the codebase or not, haven’t skimmed it yet. Screenshot is below. Btw love this idea, thanks for making it! 

![image](https://user-images.githubusercontent.com/12824100/85215595-fb19a300-b348-11ea-8b1e-f5c92e4bd043.png)

**Comment by ekzhang** [comment]
Good catch! It's still red/green if you use the light theme. In the last release we actually updated the color palette for dark theme to be more friendly for our red-green colorblind users, and I guess the colors we chose are slightly confusing if you look at the help page.

We could probably edit the help page to be less specific (e.g., in the colors list, write "red/orange, green, purple," and omit mentioning the explicit colors in the paragraph shown in the screenshot). @cynthiakedu ?

**Comment by amcdevitt97** [comment]
Oh man I didn’t ever realize it was because I was on dark theme (thanks for adding that in too btw!). Another idea could be detecting what theme the user is in, and changing the description dynamically as a result.

Finally got around to looking though the codebase and I love how you set the cards properties. First digit is color, right?

**Comment by ekzhang** [comment]
Yep, first digit is color. Cards are set this way mainly because of how Firebase Realtime Database serializes JSON data (everything -> strings), so they're easier to deal with and pass around in this form. Thanks for the suggestions!

Fixed in #20, closing this.
