### ISSUE TITLE
Race Condition Resolution

### ISSUE THREAD

**Issue by madsky** [ekzhang/setwithfriends#2]
When two players both submit the same set within a very short time space, the game allocates the set to both players.

Observed a gap of 3 seconds when registering on the score board, but not tested to establish limits, and not sure if/how this relates to the gap in set submission.

**Comment by ekzhang** [comment]
Hi @madsky, thanks for the report. This issue has been on my radar for a while, and I'm glad we now have practical evidence that it occurs. I actually took some steps to resolve this yesterday in commit a3f6681bfd0b1d20f3c71f8797eb497f332376b1, and I don't think it should be a problem anymore (you may need to hard refresh if your cache hasn't expired).

I'm closing this issue for now. If you can reproduce this bug in the future, please let me know, and it would also be helpful to provide a link to the erroneous game.
