### ISSUE TITLE
Leave cards selected when the board changes

### ISSUE THREAD

**Issue by vgautam-dialpad** [ekzhang/setwithfriends#22]
Whenever someone else finds a set and the board changes, the cards you previously selected get deselected even if they're mutually exclusive sets. It would be great to change this behaviour so that your selection only changes if it was actually affected by the other person's set.

PS it has been fantastic to be able to play set again with my friends now that we're all isolating from each other! Thank you for making this!!

**Comment by ekzhang** [comment]
Thanks for the suggestion. Unfortunately, I think we might still be keeping the current behavior. There are many possibilities to consider - for example, suppose that you have selected two cards (1 red solid diamond, 2 red solid diamond), and are about to select the last card in the set, but another player in the meantime finds the set (3 green solid diamond, 3 purple solid diamond, 3 red solid diamond). Then the last card in your set would no longer exist.

For this reason I'm closing the issue. Let me know if you can come up with a better system that addresses this though.
