### ISSUE TITLE
Make it mobile screen compatible. 

### ISSUE THREAD

**Issue by ericschmar** [ekzhang/setwithfriends#3]
Make the set board larger on mobile devices with the timer and list of sets potentially hidden or smaller.

**Comment by ekzhang** [comment]
Thanks Eric, I'm aware of this and am thinking about designs to make the site more mobile-friendly. At the moment, you can achieve most of this by rotating the screen to landscape mode and refreshing the page, although it would be interesting to think about how to display the cards well in portrait mode as well. Feel free to submit a PR.

**Comment by ericschmar** [comment]
I'm happy to take a stab at something that might work. Out of curiosity, am I able to run the front end locally or do I need to mock the backend as well?

**Comment by ekzhang** [comment]
You should be able to run the front end locally (just `npm start`); let me know if this doesn't work for you.

**Comment by ericschmar** [comment]
I've got it working now. 

It's pretty easy to get the general screens to be responsive to mobile sizes, but you're right, the cards themselves are more difficult since they are placed on the board by translating their location (based on a fraction of their size).

**Comment by ekzhang** [comment]
See #9, #10, and #11
