### ISSUE TITLE
Error: The requested `gameId` already exists

### ISSUE THREAD

**Issue by jennhu** [ekzhang/setwithfriends#31]
When I create a new game, I occasionally get the following error:

```Error: The requested `gameId` already exists.```

I usually resolve this by clicking on the "Create A Game" button until it goes away.

**Comment by ekzhang** [comment]
Thanks for the report. We fixed this a few days ago in dc5814542f42aaa4fab3bb4580b5af170213580b, and it will be live in the next version.
