### ISSUE TITLE
feature request: log in chat when someone leaves a game

### ISSUE THREAD

**Issue by eparadise** [ekzhang/setwithfriends#32]
Hi, thanks for this! I think it would be nice to put in the chat if someone has left the game. My friend and I have been playing, and one of us will leave the chat to join the next game while the other is still chatting and doesn't realize.

**Comment by ekzhang** [comment]
Good idea, this makes sense.

**Comment by gabrielatricak** [comment]
Hi, I would like to work on this issue for a school project. Can I be assigned to this?

**Comment by ekzhang** [comment]
Closing because we're not going to add this new feature at this time.
