### ISSUE TITLE
Rotate cards 90 degrees in horizontal layout

### ISSUE THREAD

**Issue by ekzhang** [ekzhang/setwithfriends#36]
Horizontal layout puts cards in an N x 3 grid, but they still lay "flat" on the page. It would be better for them to also be rotated 90 degrees, for a more even aspect ratio & potentially larger display area.

![image](https://user-images.githubusercontent.com/7550632/91522704-86229680-e8c0-11ea-8210-bc24746b6c5b.png)

**Comment by gabrielatricak** [comment]
Hi, I would like to  work on this issue for a school project. Can I be assigned to this?

**Comment by ekzhang** [comment]
@gabrielatricak, sure! I would appreciate any help. What is your level of experience with React or frontend development in general? I think you will be able to implement the functionality by looking at these two files:

- [`ResponsiveSetCard.js`](https://github.com/ekzhang/setwithfriends/blob/v2.6/src/components/ResponsiveSetCard.js)
- [`Game.js`](https://github.com/ekzhang/setwithfriends/blob/v2.6/src/components/Game.js)

Please let me know if you have any questions.

**Comment by Hanaffi** [comment]
@ekzhang Can you assign it to me?

**Comment by ekzhang** [comment]
@Hanaffi Done.

**Comment by Hanaffi** [comment]
@ekzhang  How did you get that horizontal layout?
I cant get it like your SS.

**Comment by ekzhang** [comment]
Have you tried pressing the `;` key when viewing a game on a computer?

**Comment by Hanaffi** [comment]
@ekzhang Well.
Im thinking of sending `isHorizontal` as a prop to SetCard and rotate there.
Am I correct?

**Comment by ekzhang** [comment]
Yes, you would need to pass some prop and change the rendering code. The class you want to change is `ResponsiveSetCard` though - this is the one used in the game area.

**Comment by Hanaffi** [comment]
@ekzhang Cool, Do you want to rotate the whole card or just the SVG?

**Comment by ekzhang** [comment]
Yes, both - the goal is to make the display larger and easier to use.

**Comment by Hanaffi** [comment]
![kk](https://user-images.githubusercontent.com/35642947/102687759-f64f8200-41f9-11eb-9113-065ac6ca0112.png)

I have rotated the whole card but the dimensions/styling is now a big mess!
How can I handle that?

**Comment by ekzhang** [comment]
You need to adjust the layout position of the card using some math. This is handled by a CSS `translate` property, to allow for smooth animations.

**Comment by ekzhang** [comment]
@Hanaff Any updates on this?

**Comment by Hanaffi** [comment]
@ekzhang Sorry, I had been busy with college projects and such stuff.
I will continue working on it

**Comment by Hanaffi** [comment]
@ekzhang Why do I get "Unable to connect to the server. Please try again later." when I try to `npm start`

**Comment by ekzhang** [comment]
Are you on the develop branch?

**Comment by Hanaffi** [comment]
@ekzhang  Yes, I have even tried the master one and still getting that

**Comment by Hanaffi** [comment]
@ekzhang Any idea on how to fix it?

**Comment by ekzhang** [comment]
If you're running from the master branch, you will get an error. Please run on the `develop` branch.

**Comment by Hanaffi** [comment]
@ekzhang Okay, it works now.
Why doesnt rotation work?
Im using ` transform: [{ rotate: '90deg'}] ` in style but no change.

**Comment by Hanaffi** [comment]
@ekzhang  How about that?
![zz](https://user-images.githubusercontent.com/35642947/106182187-2bf76b80-61a7-11eb-8d0f-51eab90c5402.png)

**Comment by Hanaffi** [comment]
@ekzhang  How about that?
![zz](https://user-images.githubusercontent.com/35642947/106184641-7fb78400-61aa-11eb-93dd-e75a9704cb7e.png)

**Comment by HiddeKoerts** [comment]
I think this issue can be closed :) 
@ekzhang
