### ISSUE TITLE
Creating a game as an anonymous user then signing in results results in a locked out lobby.

### ISSUE THREAD

**Issue by alvynw** [ekzhang/setwithfriends#43]
When creating a game as an anonymous user, then signing in, the anonymous user remains the game leader. The lobby does not replace the anonymous user with the signed in user. This results in losing control of the anonymous user (who is the still the game leader) meaning the lobby must be abandoned.

**Comment by ekzhang** [comment]
Hi @alvynw, thanks for your bug report. Unfortunately, we don't support merging two separate accounts together. Please create a new game.
