### ISSUE TITLE
End-of-game timing information is inconsistent with event timestamps

### ISSUE THREAD

**Issue by ekzhang** [ekzhang/setwithfriends#44]
When a game is ended, the final timer value (`games/${gameId}/endedAt`) is usually 5-50ms higher than the timestamp of the last game event (`gameData/${gameId}/events/${eventId}/time`). This is because the client takes an extra round-trip to finalize that a game has finished.

### Example

In the image below, the last event has timestamp 02:35.52, but the final timer stops at 02:35.55. There's a delay of around 30ms after the last set, before the game actually ends, and the database is updated.

![image](https://user-images.githubusercontent.com/7550632/94874695-3b90be80-0418-11eb-8fae-f58ae91a3ee6.png)

### Fixing

One solution involves adding an [HTTPS-callable serverless function](https://firebase.google.com/docs/functions/callable) to end the game, which when called, checks if the game is actually finished (and that the user is authenticated), then sets the `endedAt` key to be the time of the _last valid event_, rather than simply the _current_ time. This would resolve the visible discrepancy in timestamps.

This is a good opportunity to learn about serverless functions, realtime database permissions, and Set with Friends's architecture. Please contact me if interested.

**Comment by chrismolina159** [comment]
Hello, if this is available I would like to work on this as my first issue!

**Comment by ekzhang** [comment]
Great, thank you @chrismolina159! There are instructions for setting up your development environment in the README. You may want to start by reading these files:

- `functions/src/index.ts` - relevant documentation in https://firebase.google.com/docs/functions/callable/
- `database.rules.json` - relevant documentation in https://firebase.google.com/docs/database/security/
- `src/firebase.js`
- `src/pages/GamePage.js`- relevant documentation in https://reactjs.org/

Please let me know if you have any questions.

**Comment by chrismolina159** [comment]
@ekzhang I sent an email a few days asking for advice on a blocker that I am having.  To be more precise, it seems that I am not able to call my HTTPS callable serverless function, because the console.logs() in the function are not getting called.

I implemented a barebones version of `createGame()` and included lines similar to the ones that referenced createGame such as in `src/firebase.js` and in `pages/GamePage.js`, but when I call the function in GamePage.js, I receive an internal error and a CORS error(the internal likely causing the CORS issue?). Did you have any similar issues when creating createGame()? It is likely a small mistake causing this, but I am currently stuck.

If you need me to attach files for you to look over I can.  Thanks!

**Comment by ekzhang** [comment]
@chrismolina159 Sorry for the delay in responding. Right now, the functions require having a database connection to run, since they set up an admin connection to the realtime database. I added you as a project collaborator to the staging environment on firebase. Once you log in, you will be able to test your functions by running the following commands:

```bash
# run this once, see docs at https://firebase.google.com/docs/cli
npm install -g firebase-tools
firebase login

# in the project root directory
firebase use setwithfriends-dev
firebase deploy --only functions
```

This will deploy the functions to our staging project, which is the same environment that you see when you run `npm start` in the `develop` branch. You'll also be able to see function logs and the state of the database.

Please log in with your Google account at https://console.firebase.google.com/. I used the same account as the email you sent to me.

**Comment by chrismolina159** [comment]
![admin_needed](https://user-images.githubusercontent.com/29063542/95665946-f6107780-0b22-11eb-9dd1-462554378c1a.jpg)

It seems I need additional perms to be able to deploy any functions.  Let me know if this seems feasible or if something else is causing this error!

**Comment by ekzhang** [comment]
Thanks, I added the role for you.

**Comment by chrismolina159** [comment]
Created a PR let me know if there is anything wrong/that you want changed!
