### ISSUE TITLE
LGBTQ terms on bad word list

### ISSUE THREAD

**Issue by reislerjul** [ekzhang/setwithfriends#49]
Users are blocked from sending "lesbian" or "queer" in the chat because these are on the bad words list. There is a PR to fix this in the package you use for bad words (https://github.com/web-mech/badwords/pull/84), but there has been no movement on this PR for several months. 

You can remove these words from the bad words list yourself using the following code in `src/util.js`:
`filter.removeWords('lesbian', 'queer');`

**Comment by ekzhang** [comment]
Thanks @reislerjul.
