### ISSUE TITLE
Game thinks there's still a set to be picked?

### ISSUE THREAD

**Issue by brianc118** [ekzhang/setwithfriends#5]
Not sure what's happening here. There appears to be no sets left, but the game doesn't terminate.

![image](https://user-images.githubusercontent.com/4782836/80277414-1645a900-8732-11ea-8f7a-e8e62ff384f5.png)

**Comment by ekzhang** [comment]
Interesting! Thanks for the bug report. It looks like this can happen when two players both take sets at the same time, and that results in the game ending. I already fixed race conditions involving conflicting sets, but I guess I overlooked this case. Will try to fix when I have time (also welcome PRs!).

**Comment by ekzhang** [comment]
Fixed by #11

**Comment by mathmil** [comment]
I'm not sure if I should put this here or report a new bug, but this set-chain game doesn't end: setwithfriends.com/game/bouncy-tall-eyes-12

**Comment by mathmil** [comment]
The Problem with the game above is actually specific to firefox, it displays less and different cards than chrome/what's actually there.
Someone else recently experienced this too, you can see it in the discord. https://setwithfriends.com/game/teal-hurt-root-1
