### ISSUE TITLE
Quit button

### ISSUE THREAD

**Issue by cashpipeplusplus** [ekzhang/setwithfriends#50]
It would be wonderful to have a quit button.  When using this in an iframe pointing to a specific game code (as is done in the embedding in Gather (https://gather.town/)), once a game has begun, nobody new can join until the game is completed.  In any other context, you could go back to home and start a new game, but in context of Gather, you just have to keep going until you win.

Adding a simple "quit" button would go a long way toward improving that experience.  Thanks!

**Comment by ekzhang** [comment]
Hello, thanks for the feedback, but I'm not sure if I follow what you're saying. The embed in Gather.Town seems to just put me in the lobby at setwithfriends.com. Also, you can leave a game and go to the lobby by clicking on the "Set with Friends" logo on the top-left corner of the screen, which doubles as a home button.

Could you help me understand what you mean here?

**Comment by cashpipeplusplus** [comment]
You know, you are right.  I had forgotten that I had customized the embed in Gather to point to a specific game code.  My mistake!
