### ISSUE TITLE
enhancement: find sets in O(n^2) time

### ISSUE THREAD

**Issue by benediamond** [ekzhang/setwithfriends#52]
the current set-finding algorithm is naïve: it brute-forces all O(n^3) 3-card subsets of its n-card input deck.
https://github.com/ekzhang/setwithfriends/blob/030abe18108e83ecd7f6a5ad852eb9755888f83f/functions/src/game.ts#L77-L87
you can do better, at least asymptotically: using hashing / random access, it suffices just to iterate through all O(n^2) _2_-card subsets. indeed, for each such subset consisting of 2 cards, you can determine in constant time whether the unique 3rd card which would complete them is actually present in the deck (by calculating it, and then looking it up in a hashtable).

actually, following the algorithm on page 4 of [this paper](https://pbg.cs.illinois.edu/papers/set.pdf), you can further cut by four the constant factor. indeed, the idea is that it suffices to partition the deck into two subsets, and to only consider pairs of 2 cards both of which reside in the same subset. the algorithm is still correct, and checks much fewer pairs.

here is a write-up of the improved algorithm:
```typescript
function generateThird(a: string, b: string) {
  return Array.from({ 'length': 4 }).map((_, i) => {
    const sum = parseInt(a[i]) + parseInt(b[i]);
    return (Math.ceil((sum) / 3) * 3 - sum).toString();
  }).join("");
}

function findSet(deck: string[]) {
  const set = new Set(deck); // pardon the pun
  for (let i = 0; i < deck.length >> 1; i++) {
    for (let j = i + 1; j < deck.length >> 1; j++) {
      const third = generateThird(deck[i], deck[j]);
      if (set.has(third))
        return [deck[i], deck[j], third]
    }
  }
  for (let i = deck.length >> 1; i < deck.length; i++) {
    for (let j = i + 1; j < deck.length; j++) {
      const third = generateThird(deck[i], deck[j]);
      if (set.has(third))
        return [deck[i], deck[j], third]
    }
  }
  return null;
}
```
while this algorithm is theoretically better, it seems that in standard 4-property set the problem size is so small that it barely makes a difference. both take just ~1-2ms on a full 81-card deck. after testing both approaches, it appears that the original approach has very slightly better average-case time (about 1.3ms vs. 1.5ms). but the new approach appears to have better worst-case time (around 1.7ms vs. 2.3ms).

i'd be happy to hear your thoughts. thanks for your incredible work!

**Comment by ekzhang** [comment]
Thanks @benediamond. We're aware that you can find sets in O(n^2) time by just indexing the third card in a hash table. However, we don't see a need to do this, as n < 21 here, so all of this is actually just O(1), and we don't see any performance issues. Also, from a practical perspective, [V8](https://v8.dev/) is very good at optimizing simple nested loops. :)

The paper you linked is pretty fun. It's nice to know that 3-dimensional matching is NP-complete.

**Comment by ekzhang** [comment]
@benediamond FYI we ended up implementing this in #66, out of caution for other game modes.
