### ISSUE TITLE
Feature request: game settings

### ISSUE THREAD

**Issue by kungpaogao** [ekzhang/setwithfriends#54]
It would be cool to have some game-specific settings such as:

- guess cool down to prevent spam guesses
- overrides for user options (board rotation, disabling keybinds, color theme)
- more game stats at the end of the match (avg time to solve, number of guesses, hit rate, etc.)
- maybe a verbose mode to show every time someone guesses

I can contribute (probs over my break) if contributors are needed, although these features probably need access to some backend to test?

**Comment by ekzhang** [comment]
Thanks Andrew! We'd love to have you. The current status of the backend is that Cynthia and I are working on / experimenting with a rewrite (see `backend-rewrite` branch), but this is still in early stages.

All of your suggested features sound like they could be implemented without changing the server - user options can be stored in `window.localStorage`. Please feel free to ask if you have any questions.

**Comment by kungpaogao** [comment]
I was just thinking that it might need some backend changes because you would want to push the game settings to all users in that game?

**Comment by ekzhang** [comment]
Ah for sure. What do you think would be a good design for users being able to set options when they start a game?

**Comment by kungpaogao** [comment]
Here's a "quick" thing I made in Figma. Basically just something in the lobby is good.

![setwithfriends-settings](https://user-images.githubusercontent.com/11168401/102930073-c73f4780-4469-11eb-9468-06ed4524fe41.png)

It might be a good idea to like push to chat "Game settings changed" or something.

Not sure about database design though. Do you currently store some info linked to a game other than the link? Also, I'm sure this is probs costing you money to host at this point?

**Comment by NilsEnevoldsen** [comment]
A game-specific setting I'd like is “Autoselect third card”. When it is enabled, players would only need to select two cards from a valid set to claim the complete set.

**Comment by ekzhang** [comment]
Other relevant work on a game settings interface: #66.

**Comment by ekzhang** [comment]
I'm closing this since #66 was merged a while ago, and we have separate issues for each new game mode that people are suggesting now.
