### ISSUE TITLE
Feature request: Keyboard layout support

### ISSUE THREAD

**Issue by HiddeKoerts** [ekzhang/setwithfriends#58]
First of all, I love the project and the community you have set up. 

One thing I'd personally really like to see is support for various keyboard layouts (DVORAK / COLEMAK / AZERTY etc.). 

I have some webdev experience myself and definitely want to help further develop this project (if you'd like further help of course), and this seems like a relatively easy first issue to pick up to get more familiar with the codebase.

Am I correct in assuming that this should be possible by storing the setting locally for the user, without interacting with the database (in a similar fashion as the theme settings I think, though correct me if I'm wrong)?

**Comment by ekzhang** [comment]
Thanks for the feature request! It could definitely be done locally and would be possible to add. Right now we just store the keyboard shortcut binding as a string and toggle between them depending on layout.

My only concern about customization is how to design a simple and intuitive interface for this. Feel free to provide suggestions.

**Comment by HiddeKoerts** [comment]
Pull request #67 includes a bare bones implementation of the feature.

**Comment by HiddeKoerts** [comment]
Pull request has been merged.
