### ISSUE TITLE
Colorblind Mode

### ISSUE THREAD

**Issue by antran93** [ekzhang/setwithfriends#6]
My friend is red green colorblind and can't play this game because of the colors involved. Is there a way to make a colorblind mode of this?

**Comment by ekzhang** [comment]
Thank you very much for the suggestion! It's on our wishlist for the next major release.

**Comment by ekzhang** [comment]
Once #18 gets merged in, the dark palette (button in the top-right corner) should provide more contrast for red-green colorblind users.
