### ISSUE TITLE
Add some sound effects

### ISSUE THREAD

**Issue by Hanaffi** [ekzhang/setwithfriends#69]
Add sound effect to these events:

1. Time is about to finish.
2. When the player chooses correct set.

**Comment by ChrisCoe** [comment]
I agree that some light sound effects would add a lot to the experience. Also, the cards should not be eliminated out of the deck so quickly. Makes it hard for people to follow what just happened.

**Comment by Hanaffi** [comment]
@ekzhang Assign it to me.

**Comment by Hanaffi** [comment]
@ekzhang Assign it to me please.

**Comment by Hanaffi** [comment]
@ekzhang 
I worked on such feature easily before.
I can finish it in a day or less.
Can you assign it to me?
