### ISSUE TITLE
Keyboard features documentation

### ISSUE THREAD

**Issue by vEnhance** [ekzhang/setwithfriends#77]
On the help page, I think there should be some indication that pressing semicolon flips the layout; I had to read the source code to find this feature. (I also personally think horizontal layout should be default :P )

(In general, I think more keyboard documentation could be cool.)

**Comment by ekzhang** [comment]
I think we mention it in the help page. Horizontal layout could be the default in the future, maybe this is a good question to survey users about in Discord.

![image](https://user-images.githubusercontent.com/7550632/106691246-30ee5d80-65a1-11eb-84e2-b92a94531e0f.png)

**Comment by vEnhance** [comment]
So, guess I should RTFM :) no idea how I missed that as I did scroll through the help page. (Maybe the keyboard shortcuts could be in a different section from the gameplay rules.)

(I also grep'ped the entire repo for "horizontal" and "semicolon" and neither of those worked. Should've grep'ped "keyboard"!)
