### ISSUE TITLE
UltraSet UI incorrectly makes a set

### ISSUE THREAD

**Issue by phayv** [ekzhang/setwithfriends#83]
In the UltraSet mode, it seems the UI is incorrect in identifying the actual card. In the identified UltraSet, the open squiggles card was not on the board. Even after identifying the UltraSet, the card should still remain on the board. That was not the case either. Before and after, the card was not on the board. Instead the striped squiggles was the only one available to make a set.

![Screen Shot 2021-02-03 at 10 30 40 PM](https://user-images.githubusercontent.com/17148586/106854540-54cca480-6670-11eb-87d8-1c8c6b4173fd.png)

**Comment by ekzhang** [comment]
It doesn't need to be on the board. See the [help page](https://setwithfriends.com/help).
