### ISSUE TITLE
Whats New

### ISSUE THREAD

**Issue by Hanaffi** [ekzhang/setwithfriends#92]
Can we have like a modal/pop-up after each release/patch showing what has been added to the website?
So that users can notice changes.

If its a good idea , Assign it to me

**Comment by ekzhang** [comment]
Probably a good idea, not sure how to make this fit in given that we already show a `WelcomeDialog` to new users though. We would need to have a way to make sure these don't overlap, for example. Or maybe just combine them into one.

**Comment by cynthiakedu** [comment]
Perhaps one thing we can try to do is imitating how Codeforces gives sitewide announcements (I found an example of the announcement in google images, shown below). This isn't really a modal/pop-up. A user can click on the x on the top right of the box to make an announcement disappear. Though this still runs into the issue of perhaps overwhelming users.

![codeforces notification](https://user-images.githubusercontent.com/47993494/109427315-d093e580-79bf-11eb-8f2e-f19b24997f2f.jpg)

**Comment by Hanaffi** [comment]
> Probably a good idea, not sure how to make this fit in given that we already show a `WelcomeDialog` to new users though. We would need to have a way to make sure these don't overlap, for example. Or maybe just combine them into one.
@ekzhang  @cynthiakedu 
What came first to my mind is that we can store some info about the user so that we can distinguish if its the first time to play the game or not.
{
user: {
ip_address, //or smth like that (to refer to some user, since we dont have accounts here)
state
}
}

state=0 if this is the first time to visit the website
state=1 , old player but first time after the update
state=2 , old player and already played after the update before


if state = 0 :
show the walkthrough or Welcome dialog & set state to 1

if state = 1:
show the WhatsNew Modal & set state to 2

if state = 2:
dont show anything

 
After each update we loop through this table and set all users state to 1.

Does that make sense?

**Comment by ekzhang** [comment]
Implemented in https://github.com/ekzhang/setwithfriends/commit/681f974de2bda461d62f735488701e92f2c65ed3, see the settings menu. It now contains the current version number and a link to the release notes.
