### ISSUE TITLE
More casual game mode

### ISSUE THREAD

**Issue by darrylyong** [ekzhang/setwithfriends#97]
Classrooms all over the world are happening remotely and teachers are looking for ways to connect with students in fun ways. Setwithfriends is already a wonderful way for this to happen, but the experience might be enhanced with a more casual game mode that:

- removes the score board (or has a toggle for it, so that we can have less competitive play to encourage more participation)
- allows for students to join a private room even after the waiting room is already closed (right now if you join after the waiting room you can only spectate)

Thanks for considering it!

**Comment by ekzhang** [comment]
Thanks for the suggestions, we considered your proposal and unfortunately do not think it will be worked on.
