### ISSUE TITLE
Monetization

### ISSUE THREAD

**Issue by ekzhang** [ekzhang/setwithfriends#99]
People aren't really donating enough right now, barely enough to keep servers running at current usage levels. Could have more time to make the game better if there Set with Friends just captured 10x more revenue or so. Potential options:

- Google Adsense (~$1000-$2000/mo), possibly tricky to set up for dynamic content
- Premium features, >90% of games played on the site are private right now, can limit to X private games per day

**Comment by shagemey** [comment]
Out of curiosity, what does it cost per month to keep set with friends up and running?

**Comment by ekzhang** [comment]
Decided that ads are probably not worth implementing at this point.
